// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozrzyrjfvldfvxtdaodw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cnp5cmpmdmxkZnZ4dGRhb2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODQzMDEsImV4cCI6MjA2MzM2MDMwMX0.Qz9IMnRiMHKUepqH6xnXiQc1r4o2mjG8yWu5jvDVIkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);